// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAuditLog(arg1, arg2) {
  return window['go']['app']['App']['AddAuditLog'](arg1, arg2);
}

export function AddHost(arg1) {
  return window['go']['app']['App']['AddHost'](arg1);
}

export function AppendExecutionLog(arg1, arg2) {
  return window['go']['app']['App']['AppendExecutionLog'](arg1, arg2);
}

export function CheckConnectivity(arg1) {
  return window['go']['app']['App']['CheckConnectivity'](arg1);
}

export function CheckIperfInstalled(arg1) {
  return window['go']['app']['App']['CheckIperfInstalled'](arg1);
}

export function CheckIperfServer(arg1, arg2) {
  return window['go']['app']['App']['CheckIperfServer'](arg1, arg2);
}

export function CheckIperfTestStatus(arg1) {
  return window['go']['app']['App']['CheckIperfTestStatus'](arg1);
}

export function CheckStatus(arg1, arg2) {
  return window['go']['app']['App']['CheckStatus'](arg1, arg2);
}

export function CleanIperfLocal(arg1) {
  return window['go']['app']['App']['CleanIperfLocal'](arg1);
}

export function CleanIperfRemote(arg1) {
  return window['go']['app']['App']['CleanIperfRemote'](arg1);
}

export function CleanLocal(arg1) {
  return window['go']['app']['App']['CleanLocal'](arg1);
}

export function CleanRemote(arg1, arg2) {
  return window['go']['app']['App']['CleanRemote'](arg1, arg2);
}

export function ClearExecutionLog(arg1) {
  return window['go']['app']['App']['ClearExecutionLog'](arg1);
}

export function CompareTaskMetrics(arg1) {
  return window['go']['app']['App']['CompareTaskMetrics'](arg1);
}

export function CreateIperfTask(arg1) {
  return window['go']['app']['App']['CreateIperfTask'](arg1);
}

export function CreateReportZIP(arg1) {
  return window['go']['app']['App']['CreateReportZIP'](arg1);
}

export function DeleteExecutionTask(arg1) {
  return window['go']['app']['App']['DeleteExecutionTask'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['app']['App']['DeleteHost'](arg1);
}

export function DeleteIperfConfig(arg1) {
  return window['go']['app']['App']['DeleteIperfConfig'](arg1);
}

export function DeleteIperfTask(arg1) {
  return window['go']['app']['App']['DeleteIperfTask'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['app']['App']['DeleteScript'](arg1);
}

export function DeleteScriptConfig(arg1) {
  return window['go']['app']['App']['DeleteScriptConfig'](arg1);
}

export function Deploy(arg1, arg2, arg3) {
  return window['go']['app']['App']['Deploy'](arg1, arg2, arg3);
}

export function DeployMulti(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeployMulti'](arg1, arg2, arg3);
}

export function ExecuteOrchestration(arg1, arg2) {
  return window['go']['app']['App']['ExecuteOrchestration'](arg1, arg2);
}

export function GenerateIperfReport(arg1) {
  return window['go']['app']['App']['GenerateIperfReport'](arg1);
}

export function GenerateReport(arg1) {
  return window['go']['app']['App']['GenerateReport'](arg1);
}

export function GenerateReportPDF(arg1) {
  return window['go']['app']['App']['GenerateReportPDF'](arg1);
}

export function GetAnalysisTasks() {
  return window['go']['app']['App']['GetAnalysisTasks']();
}

export function GetAuditLog() {
  return window['go']['app']['App']['GetAuditLog']();
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetExecutionLog(arg1) {
  return window['go']['app']['App']['GetExecutionLog'](arg1);
}

export function GetExecutionTasks() {
  return window['go']['app']['App']['GetExecutionTasks']();
}

export function GetHostLog(arg1, arg2) {
  return window['go']['app']['App']['GetHostLog'](arg1, arg2);
}

export function GetHosts() {
  return window['go']['app']['App']['GetHosts']();
}

export function GetIperfAnalysisTasks() {
  return window['go']['app']['App']['GetIperfAnalysisTasks']();
}

export function GetIperfConfig(arg1) {
  return window['go']['app']['App']['GetIperfConfig'](arg1);
}

export function GetIperfConfigs() {
  return window['go']['app']['App']['GetIperfConfigs']();
}

export function GetIperfIntervals(arg1) {
  return window['go']['app']['App']['GetIperfIntervals'](arg1);
}

export function GetIperfReportHTML(arg1) {
  return window['go']['app']['App']['GetIperfReportHTML'](arg1);
}

export function GetIperfTaskLog(arg1) {
  return window['go']['app']['App']['GetIperfTaskLog'](arg1);
}

export function GetIperfTasks() {
  return window['go']['app']['App']['GetIperfTasks']();
}

export function GetOrchestrationConfig() {
  return window['go']['app']['App']['GetOrchestrationConfig']();
}

export function GetReportHTML(arg1) {
  return window['go']['app']['App']['GetReportHTML'](arg1);
}

export function GetReportHTMLWithEcharts(arg1) {
  return window['go']['app']['App']['GetReportHTMLWithEcharts'](arg1);
}

export function GetScriptConfig(arg1) {
  return window['go']['app']['App']['GetScriptConfig'](arg1);
}

export function GetScriptContent(arg1) {
  return window['go']['app']['App']['GetScriptContent'](arg1);
}

export function GetScripts() {
  return window['go']['app']['App']['GetScripts']();
}

export function IsIperfMonitorRunning(arg1) {
  return window['go']['app']['App']['IsIperfMonitorRunning'](arg1);
}

export function KillAll(arg1, arg2) {
  return window['go']['app']['App']['KillAll'](arg1, arg2);
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function PreDeployCheck(arg1, arg2) {
  return window['go']['app']['App']['PreDeployCheck'](arg1, arg2);
}

export function PullData(arg1, arg2) {
  return window['go']['app']['App']['PullData'](arg1, arg2);
}

export function PullIperfData(arg1) {
  return window['go']['app']['App']['PullIperfData'](arg1);
}

export function PullTaskData(arg1) {
  return window['go']['app']['App']['PullTaskData'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['app']['App']['RevealFile'](arg1);
}

export function RunIperfTest(arg1) {
  return window['go']['app']['App']['RunIperfTest'](arg1);
}

export function SaveExecutionTasks(arg1) {
  return window['go']['app']['App']['SaveExecutionTasks'](arg1);
}

export function SaveIperfConfig(arg1) {
  return window['go']['app']['App']['SaveIperfConfig'](arg1);
}

export function SaveOrchestrationConfig(arg1) {
  return window['go']['app']['App']['SaveOrchestrationConfig'](arg1);
}

export function SaveScript(arg1, arg2) {
  return window['go']['app']['App']['SaveScript'](arg1, arg2);
}

export function SaveScriptConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveScriptConfig'](arg1, arg2);
}

export function SetTaskFinished(arg1) {
  return window['go']['app']['App']['SetTaskFinished'](arg1);
}

export function SetTaskStarted(arg1) {
  return window['go']['app']['App']['SetTaskStarted'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartIperfServer(arg1, arg2) {
  return window['go']['app']['App']['StartIperfServer'](arg1, arg2);
}

export function StopIperfServer(arg1, arg2) {
  return window['go']['app']['App']['StopIperfServer'](arg1, arg2);
}

export function StopIperfTest(arg1) {
  return window['go']['app']['App']['StopIperfTest'](arg1);
}

export function UpdateHost(arg1, arg2) {
  return window['go']['app']['App']['UpdateHost'](arg1, arg2);
}

export function MonitorFioTask(arg1, arg2) {
  return window['go']['app']['App']['MonitorFioTask'](arg1, arg2);
}

export function StopFioMonitor(arg1) {
  return window['go']['app']['App']['StopFioMonitor'](arg1);
}

export function GenerateReportPDF(arg1) {
  return window['go']['app']['App']['GenerateReportPDF'](arg1);
}
