// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAuditLog(arg1, arg2) {
  return window['go']['app']['App']['AddAuditLog'](arg1, arg2);
}

export function AddHost(arg1) {
  return window['go']['app']['App']['AddHost'](arg1);
}

export function AppendExecutionLog(arg1, arg2) {
  return window['go']['app']['App']['AppendExecutionLog'](arg1, arg2);
}

export function CheckConnectivity(arg1) {
  return window['go']['app']['App']['CheckConnectivity'](arg1);
}

export function CheckStatus(arg1, arg2) {
  return window['go']['app']['App']['CheckStatus'](arg1, arg2);
}

export function CleanLocal(arg1) {
  return window['go']['app']['App']['CleanLocal'](arg1);
}

export function CleanRemote(arg1, arg2) {
  return window['go']['app']['App']['CleanRemote'](arg1, arg2);
}

export function ClearExecutionLog(arg1) {
  return window['go']['app']['App']['ClearExecutionLog'](arg1);
}

export function CreateReportZIP(arg1) {
  return window['go']['app']['App']['CreateReportZIP'](arg1);
}

export function DeleteExecutionTask(arg1) {
  return window['go']['app']['App']['DeleteExecutionTask'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['app']['App']['DeleteHost'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['app']['App']['DeleteScript'](arg1);
}

export function DeleteScriptConfig(arg1) {
  return window['go']['app']['App']['DeleteScriptConfig'](arg1);
}

export function Deploy(arg1, arg2, arg3) {
  return window['go']['app']['App']['Deploy'](arg1, arg2, arg3);
}

export function DeployMulti(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeployMulti'](arg1, arg2, arg3);
}

export function ExecuteOrchestration(arg1, arg2) {
  return window['go']['app']['App']['ExecuteOrchestration'](arg1, arg2);
}

export function GenerateReport(arg1) {
  return window['go']['app']['App']['GenerateReport'](arg1);
}

export function GetAnalysisTasks() {
  return window['go']['app']['App']['GetAnalysisTasks']();
}

export function GetAuditLog() {
  return window['go']['app']['App']['GetAuditLog']();
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetExecutionLog(arg1) {
  return window['go']['app']['App']['GetExecutionLog'](arg1);
}

export function GetExecutionTasks() {
  return window['go']['app']['App']['GetExecutionTasks']();
}

export function GetHostLog(arg1, arg2) {
  return window['go']['app']['App']['GetHostLog'](arg1, arg2);
}

export function GetHosts() {
  return window['go']['app']['App']['GetHosts']();
}

export function GetOrchestrationConfig() {
  return window['go']['app']['App']['GetOrchestrationConfig']();
}

export function GetReportHTML(arg1) {
  return window['go']['app']['App']['GetReportHTML'](arg1);
}

export function GetReportHTMLWithEcharts(arg1) {
  return window['go']['app']['App']['GetReportHTMLWithEcharts'](arg1);
}

export function GetScriptConfig(arg1) {
  return window['go']['app']['App']['GetScriptConfig'](arg1);
}

export function GetScriptContent(arg1) {
  return window['go']['app']['App']['GetScriptContent'](arg1);
}

export function GetScripts() {
  return window['go']['app']['App']['GetScripts']();
}

export function KillAll(arg1, arg2) {
  return window['go']['app']['App']['KillAll'](arg1, arg2);
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function PreDeployCheck(arg1, arg2) {
  return window['go']['app']['App']['PreDeployCheck'](arg1, arg2);
}

export function PullData(arg1, arg2) {
  return window['go']['app']['App']['PullData'](arg1, arg2);
}

export function PullTaskData(arg1) {
  return window['go']['app']['App']['PullTaskData'](arg1);
}

export function SaveExecutionTasks(arg1) {
  return window['go']['app']['App']['SaveExecutionTasks'](arg1);
}

export function SaveOrchestrationConfig(arg1) {
  return window['go']['app']['App']['SaveOrchestrationConfig'](arg1);
}

export function SaveScript(arg1, arg2) {
  return window['go']['app']['App']['SaveScript'](arg1, arg2);
}

export function SaveScriptConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveScriptConfig'](arg1, arg2);
}

export function SetTaskFinished(arg1) {
  return window['go']['app']['App']['SetTaskFinished'](arg1);
}

export function SetTaskStarted(arg1) {
  return window['go']['app']['App']['SetTaskStarted'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function UpdateHost(arg1, arg2) {
  return window['go']['app']['App']['UpdateHost'](arg1, arg2);
}
