// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {executor} from '../models';
import {app} from '../models';
import {context} from '../models';

export function AddAuditLog(arg1:string,arg2:string):Promise<void>;

export function AddHost(arg1:executor.HostConfig):Promise<number>;

export function AppendExecutionLog(arg1:string,arg2:string):Promise<void>;

export function CheckConnectivity(arg1:executor.HostConfig):Promise<app.ConnectivityResult>;

export function CheckStatus(arg1:string,arg2:Array<executor.HostConfig>):Promise<Array<app.ActionResult>>;

export function CleanLocal(arg1:string):Promise<void>;

export function CleanRemote(arg1:string,arg2:Array<executor.HostConfig>):Promise<Array<app.ActionResult>>;

export function CreateReportZIP(arg1:string):Promise<string>;

export function DeleteExecutionTask(arg1:string):Promise<void>;

export function DeleteHost(arg1:number):Promise<void>;

export function DeleteScript(arg1:string):Promise<void>;

export function DeleteScriptConfig(arg1:string):Promise<void>;

export function Deploy(arg1:string,arg2:string,arg3:Array<executor.HostConfig>):Promise<Array<app.ActionResult>>;

export function DeployMulti(arg1:string,arg2:Array<string>,arg3:Array<executor.HostConfig>):Promise<Array<app.ActionResult>>;

export function ExecuteOrchestration(arg1:Array<string>,arg2:number):Promise<Array<app.OrchestrationProgress>>;

export function GenerateReport(arg1:string):Promise<string>;

export function GetAnalysisTasks():Promise<Array<app.AnalysisSummary>>;

export function GetAuditLog():Promise<Array<app.AuditEntry>>;

export function GetExecutionLog(arg1:string):Promise<string>;

export function GetExecutionTasks():Promise<Array<app.ExecutionTaskConfig>>;

export function GetDataDir():Promise<string>;

export function GetHostLog(arg1:string,arg2:string):Promise<string>;

export function GetHosts():Promise<Array<app.HostRecord>>;

export function GetOrchestrationConfig():Promise<app.OrchestrationConfig>;

export function GetReportHTML(arg1:string):Promise<string>;

export function GetReportHTMLWithEcharts(arg1:string):Promise<string>;

export function GetScriptConfig(arg1:string):Promise<string>;

export function GetScriptContent(arg1:string):Promise<string>;

export function GetScripts():Promise<Array<string>>;

export function KillAll(arg1:string,arg2:Array<executor.HostConfig>):Promise<Array<app.ActionResult>>;

export function OpenDataDir():Promise<void>;

export function PreDeployCheck(arg1:string,arg2:Array<executor.HostConfig>):Promise<Array<app.CheckResult>>;

export function PullData(arg1:string,arg2:Array<executor.HostConfig>):Promise<Array<app.ActionResult>>;

export function PullTaskData(arg1:string):Promise<Array<app.ActionResult>>;

export function SaveExecutionTasks(arg1:Array<app.ExecutionTaskConfig>):Promise<void>;

export function SaveOrchestrationConfig(arg1:app.OrchestrationConfig):Promise<void>;

export function SaveScript(arg1:string,arg2:string):Promise<void>;

export function SaveScriptConfig(arg1:string,arg2:string):Promise<void>;

export function SetTaskFinished(arg1:string):Promise<void>;

export function SetTaskStarted(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function UpdateHost(arg1:number,arg2:executor.HostConfig):Promise<void>;
