// Auto-generated Wails bindings for App struct
// DO NOT EDIT - regenerated by Wails CLI

export function GetScripts(): Promise<string[]>;
export function GetScriptContent(name: string): Promise<string>;
export function SaveScript(name: string, content: string): Promise<void>;
export function DeleteScript(name: string): Promise<void>;
export function SaveScriptConfig(scriptName: string, configJSON: string): Promise<void>;
export function GetScriptConfig(scriptName: string): Promise<string>;
export function DeleteScriptConfig(scriptName: string): Promise<void>;
export function GetExecutionTasks(): Promise<ExecutionTaskConfig[]>;
export function SaveExecutionTasks(tasks: ExecutionTaskConfig[]): Promise<void>;
export function CheckConnectivity(host: HostConfig): Promise<{ok: boolean, msg: string}>;
export function PreDeployCheck(taskID: string, hosts: HostConfig[]): Promise<CheckResult[]>;
export function Deploy(taskID: string, scriptName: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function DeployMulti(taskID: string, scripts: string[], hosts: HostConfig[]): Promise<ActionResult[]>;
export function CheckStatus(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function KillAll(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function PullData(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function CleanLocal(taskID: string): Promise<void>;
export function CleanRemote(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function GetAnalysisTasks(): Promise<AnalysisSummary[]>;
export function GenerateReport(taskID: string): Promise<string>;
export function GetReportHTML(taskID: string): Promise<string>;
export function GetOrchestrationConfig(): Promise<OrchestrationConfig>;
export function SaveOrchestrationConfig(config: OrchestrationConfig): Promise<void>;
export function GetAuditLog(): Promise<AuditEntry[]>;
export function AddAuditLog(action: string, details: string): Promise<void>;
export function GetExecutionLog(taskID: string): Promise<string>;
export function GetHostLog(taskID: string, hostStr: string): Promise<string>;
export function ExecuteOrchestration(taskIDs: string[], interval: number): Promise<OrchestrationProgress[]>;
export function CreateReportZIP(taskID: string): Promise<string>;
export function GetReportHTMLWithEcharts(taskID: string): Promise<string>;

export function AddHost(host: HostConfig): Promise<number>;
export function GetHosts(): Promise<HostRecord[]>;
export function DeleteHost(id: number): Promise<void>;
export function UpdateHost(id: number, host: HostConfig): Promise<void>;

export interface HostConfig {
    host: string;
    port: number;
    user: string;
    password: string;
}

export interface HostRecord {
    id: number;
    host: string;
    port: number;
    user: string;
    password: string;
}

export interface ExecutionTaskConfig {
    id: string;
    name: string;
    scripts: string[];
    hosts: HostConfig[];
}

export interface CheckResult {
    host: string;
    running: boolean;
    residual: boolean;
    msg: string;
}

export interface ActionResult {
    host: string;
    error: string;
    msg: string;
    running: boolean;
}

export interface AnalysisSummary {
    id: string;
    name: string;
    scripts: string[];
    hasData: boolean;
    hasReport: boolean;
    logAvailable: boolean;
    dataDir: string;
    reportDir: string;
    reportHtmlUrl: string;
    downloadUrl: string;
}

export interface OrchestrationConfig {
    sequence: string[];
    interval: number;
}

export interface AuditEntry {
    action: string;
    details: string;
    timestamp: string;
}

export interface OrchestrationProgress {
    taskId: string;
    taskName: string;
    step: string;
    status: string;
    error: string;
    results: ActionResult[];
    current: number;
    total: number;
}
