// Auto-generated Wails bindings for App struct
// DO NOT EDIT - regenerated by Wails CLI

export function GetScripts() {
    return window['go']['app']['App']['GetScripts']();
}

export function GetScriptContent(name) {
    return window['go']['app']['App']['GetScriptContent'](name);
}

export function SaveScript(name, content) {
    return window['go']['app']['App']['SaveScript'](name, content);
}

export function DeleteScript(name) {
    return window['go']['app']['App']['DeleteScript'](name);
}

export function GetExecutionTasks() {
    return window['go']['app']['App']['GetExecutionTasks']();
}

export function SaveExecutionTasks(tasks) {
    return window['go']['app']['App']['SaveExecutionTasks'](tasks);
}

export function CheckConnectivity(host) {
    return window['go']['app']['App']['CheckConnectivity'](host);
}

export function PreDeployCheck(taskID, hosts) {
    return window['go']['app']['App']['PreDeployCheck'](taskID, hosts);
}

export function Deploy(taskID, scriptName, hosts) {
    return window['go']['app']['App']['Deploy'](taskID, scriptName, hosts);
}

export function CheckStatus(taskID, hosts) {
    return window['go']['app']['App']['CheckStatus'](taskID, hosts);
}

export function KillAll(taskID, hosts) {
    return window['go']['app']['App']['KillAll'](taskID, hosts);
}

export function PullData(taskID, hosts) {
    return window['go']['app']['App']['PullData'](taskID, hosts);
}

export function CleanLocal(taskID) {
    return window['go']['app']['App']['CleanLocal'](taskID);
}

export function CleanRemote(taskID, hosts) {
    return window['go']['app']['App']['CleanRemote'](taskID, hosts);
}

export function GetAnalysisTasks() {
    return window['go']['app']['App']['GetAnalysisTasks']();
}

export function GenerateReport(taskID) {
    return window['go']['app']['App']['GenerateReport'](taskID);
}

export function GetReportHTML(taskID) {
    return window['go']['app']['App']['GetReportHTML'](taskID);
}

export function GetOrchestrationConfig() {
    return window['go']['app']['App']['GetOrchestrationConfig']();
}

export function SaveOrchestrationConfig(config) {
    return window['go']['app']['App']['SaveOrchestrationConfig'](config);
}

export function GetAuditLog() {
    return window['go']['app']['App']['GetAuditLog']();
}

export function AddAuditLog(action, details) {
    return window['go']['app']['App']['AddAuditLog'](action, details);
}

export function GetExecutionLog(taskID) {
    return window['go']['app']['App']['GetExecutionLog'](taskID);
}

export function GetHostLog(taskID, hostStr) {
    return window['go']['app']['App']['GetHostLog'](taskID, hostStr);
}

export function ExecuteOrchestration(taskIDs, interval) {
    return window['go']['app']['App']['ExecuteOrchestration'](taskIDs, interval);
}

export function CreateReportZIP(taskID) {
    return window['go']['app']['App']['CreateReportZIP'](taskID);
}

export function GetReportHTMLWithEcharts(taskID) {
    return window['go']['app']['App']['GetReportHTMLWithEcharts'](taskID);
}

export function AddHost(host) {
    return window['go']['app']['App']['AddHost'](host);
}

export function GetHosts() {
    return window['go']['app']['App']['GetHosts']();
}

export function DeleteHost(id) {
    return window['go']['app']['App']['DeleteHost'](id);
}

export function UpdateHost(id, host) {
    return window['go']['app']['App']['UpdateHost'](id, host);
}
