// Auto-generated Wails bindings for App struct
// DO NOT EDIT - regenerated by Wails CLI

export function GetScripts() {
    return window['go']['app']['App']['GetScripts']();
}

export function GetScriptContent(name) {
    return window['go']['app']['App']['GetScriptContent'](name);
}

export function SaveScript(name, content) {
    return window['go']['app']['App']['SaveScript'](name, content);
}

export function DeleteScript(name) {
    return window['go']['app']['App']['DeleteScript'](name);
}

export function SaveScriptConfig(scriptName, configJSON) {
    return window['go']['app']['App']['SaveScriptConfig'](scriptName, configJSON);
}

export function GetScriptConfig(scriptName) {
    return window['go']['app']['App']['GetScriptConfig'](scriptName);
}

export function DeleteScriptConfig(scriptName) {
    return window['go']['app']['App']['DeleteScriptConfig'](scriptName);
}

export function GetExecutionTasks() {
    return window['go']['app']['App']['GetExecutionTasks']();
}

export function SaveExecutionTasks(tasks) {
    return window['go']['app']['App']['SaveExecutionTasks'](tasks);
}

export function DeleteExecutionTask(taskID) {
    return window['go']['app']['App']['DeleteExecutionTask'](taskID);
}

export function SetTaskStarted(taskID) {
    return window['go']['app']['App']['SetTaskStarted'](taskID);
}

export function SetTaskFinished(taskID) {
    return window['go']['app']['App']['SetTaskFinished'](taskID);
}

export function CheckConnectivity(host) {
    return window['go']['app']['App']['CheckConnectivity'](host);
}

export function PreDeployCheck(taskID, hosts) {
    return window['go']['app']['App']['PreDeployCheck'](taskID, hosts);
}

export function Deploy(taskID, scriptName, hosts) {
    return window['go']['app']['App']['Deploy'](taskID, scriptName, hosts);
}

export function DeployMulti(taskID, scripts, hosts) {
    return window['go']['app']['App']['DeployMulti'](taskID, scripts, hosts);
}

export function CheckStatus(taskID, hosts) {
    return window['go']['app']['App']['CheckStatus'](taskID, hosts);
}

export function KillAll(taskID, hosts) {
    return window['go']['app']['App']['KillAll'](taskID, hosts);
}

export function PullData(taskID, hosts) {
    return window['go']['app']['App']['PullData'](taskID, hosts);
}

export function PullTaskData(taskID) {
    return window['go']['app']['App']['PullTaskData'](taskID);
}

export function CleanLocal(taskID) {
    return window['go']['app']['App']['CleanLocal'](taskID);
}

export function CleanRemote(taskID, hosts) {
    return window['go']['app']['App']['CleanRemote'](taskID, hosts);
}

export function GetAnalysisTasks() {
    return window['go']['app']['App']['GetAnalysisTasks']();
}

export function GenerateReport(taskID) {
    return window['go']['app']['App']['GenerateReport'](taskID);
}

export function GetReportHTML(taskID) {
    return window['go']['app']['App']['GetReportHTML'](taskID);
}

export function GetOrchestrationConfig() {
    return window['go']['app']['App']['GetOrchestrationConfig']();
}

export function SaveOrchestrationConfig(config) {
    return window['go']['app']['App']['SaveOrchestrationConfig'](config);
}

export function GetAuditLog() {
    return window['go']['app']['App']['GetAuditLog']();
}

export function AddAuditLog(action, details) {
    return window['go']['app']['App']['AddAuditLog'](action, details);
}

export function GetExecutionLog(taskID) {
    return window['go']['app']['App']['GetExecutionLog'](taskID);
}

export function GetHostLog(taskID, hostStr) {
    return window['go']['app']['App']['GetHostLog'](taskID, hostStr);
}

export function ExecuteOrchestration(taskIDs, interval) {
    return window['go']['app']['App']['ExecuteOrchestration'](taskIDs, interval);
}

export function CreateReportZIP(taskID) {
    return window['go']['app']['App']['CreateReportZIP'](taskID);
}

export function GetReportHTMLWithEcharts(taskID) {
    return window['go']['app']['App']['GetReportHTMLWithEcharts'](taskID);
}

export function GetDataDir() {
    return window['go']['app']['App']['GetDataDir']();
}

export function OpenDataDir() {
    return window['go']['app']['App']['OpenDataDir']();
}

export function OpenFile(path) {
    return window['go']['app']['App']['OpenFile'](path);
}

export function RevealFile(path) {
    return window['go']['app']['App']['RevealFile'](path);
}

export function AddHost(host) {
    return window['go']['app']['App']['AddHost'](host);
}

export function AppendExecutionLog(taskID, message) {
    return window['go']['app']['App']['AppendExecutionLog'](taskID, message);
}

export function GetHosts() {
    return window['go']['app']['App']['GetHosts']();
}

export function DeleteHost(id) {
    return window['go']['app']['App']['DeleteHost'](id);
}

export function UpdateHost(id, host) {
    return window['go']['app']['App']['UpdateHost'](id, host);
}

export function SaveIperfConfig(config) {
    return window['go']['app']['App']['SaveIperfConfig'](config);
}

export function GetIperfConfigs() {
    return window['go']['app']['App']['GetIperfConfigs']();
}

export function GetIperfConfig(id) {
    return window['go']['app']['App']['GetIperfConfig'](id);
}

export function DeleteIperfConfig(id) {
    return window['go']['app']['App']['DeleteIperfConfig'](id);
}

export function CreateIperfTask(task) {
    return window['go']['app']['App']['CreateIperfTask'](task);
}

export function GetIperfTasks() {
    return window['go']['app']['App']['GetIperfTasks']();
}

export function DeleteIperfTask(id) {
    return window['go']['app']['App']['DeleteIperfTask'](id);
}

export function StartIperfServer(host, port) {
    return window['go']['app']['App']['StartIperfServer'](host, port);
}

export function StopIperfServer(host, port) {
    return window['go']['app']['App']['StopIperfServer'](host, port);
}

export function CheckIperfServer(host, port) {
    return window['go']['app']['App']['CheckIperfServer'](host, port);
}

export function CheckIperfInstalled(hosts) {
    return window['go']['app']['App']['CheckIperfInstalled'](hosts);
}

export function RunIperfTest(taskID) {
    return window['go']['app']['App']['RunIperfTest'](taskID);
}

export function StopIperfTest(taskID) {
    return window['go']['app']['App']['StopIperfTest'](taskID);
}

export function CheckIperfTestStatus(taskID) {
    return window['go']['app']['App']['CheckIperfTestStatus'](taskID);
}

export function IsIperfMonitorRunning(taskID) {
    return window['go']['app']['App']['IsIperfMonitorRunning'](taskID);
}

export function PullIperfData(taskID) {
    return window['go']['app']['App']['PullIperfData'](taskID);
}

export function GenerateIperfReport(taskID) {
    return window['go']['app']['App']['GenerateIperfReport'](taskID);
}

export function GetIperfReportHTML(taskID) {
    return window['go']['app']['App']['GetIperfReportHTML'](taskID);
}

export function GetIperfAnalysisTasks() {
    return window['go']['app']['App']['GetIperfAnalysisTasks']();
}

export function CleanIperfLocal(taskID) {
    return window['go']['app']['App']['CleanIperfLocal'](taskID);
}

export function CleanIperfRemote(taskID) {
    return window['go']['app']['App']['CleanIperfRemote'](taskID);
}

export function GetIperfIntervals(taskID) {
    return window['go']['app']['App']['GetIperfIntervals'](taskID);
}

export function GetIperfTaskLog(taskID) {
    return window['go']['app']['App']['GetIperfTaskLog'](taskID);
}
