// Auto-generated Wails bindings for App struct
// DO NOT EDIT - regenerated by Wails CLI

export function GetScripts(): Promise<string[]>;
export function GetScriptContent(name: string): Promise<string>;
export function SaveScript(name: string, content: string): Promise<void>;
export function DeleteScript(name: string): Promise<void>;
export function SaveScriptConfig(scriptName: string, configJSON: string): Promise<void>;
export function GetScriptConfig(scriptName: string): Promise<string>;
export function DeleteScriptConfig(scriptName: string): Promise<void>;
export function GetExecutionTasks(): Promise<ExecutionTaskConfig[]>;
export function SaveExecutionTasks(tasks: ExecutionTaskConfig[]): Promise<void>;
export function DeleteExecutionTask(taskID: string): Promise<void>;
export function SetTaskStarted(taskID: string): Promise<void>;
export function SetTaskFinished(taskID: string): Promise<void>;
export function CheckConnectivity(host: HostConfig): Promise<{ok: boolean, msg: string}>;
export function PreDeployCheck(taskID: string, hosts: HostConfig[]): Promise<CheckResult[]>;
export function Deploy(taskID: string, scriptName: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function DeployMulti(taskID: string, scripts: string[], hosts: HostConfig[]): Promise<ActionResult[]>;
export function CheckStatus(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function KillAll(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function PullData(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function PullTaskData(taskID: string): Promise<ActionResult[]>;
export function CleanLocal(taskID: string): Promise<void>;
export function CleanRemote(taskID: string, hosts: HostConfig[]): Promise<ActionResult[]>;
export function GetAnalysisTasks(): Promise<AnalysisSummary[]>;
export function GenerateReport(taskID: string): Promise<string>;
export function GetReportHTML(taskID: string): Promise<string>;
export function GetOrchestrationConfig(): Promise<OrchestrationConfig>;
export function SaveOrchestrationConfig(config: OrchestrationConfig): Promise<void>;
export function GetAuditLog(): Promise<AuditEntry[]>;
export function AddAuditLog(action: string, details: string): Promise<void>;
export function GetExecutionLog(taskID: string): Promise<string>;
export function GetHostLog(taskID: string, hostStr: string): Promise<string>;
export function ExecuteOrchestration(taskIDs: string[], interval: number): Promise<OrchestrationProgress[]>;
export function CreateReportZIP(taskID: string): Promise<string>;
export function GetReportHTMLWithEcharts(taskID: string): Promise<string>;

export function GetDataDir(): Promise<string>;
export function OpenDataDir(): Promise<void>;
export function OpenFile(path: string): Promise<void>;
export function RevealFile(path: string): Promise<void>;

export function AddHost(host: HostConfig): Promise<number>;
export function AppendExecutionLog(taskID: string, message: string): Promise<void>;
export function GetHosts(): Promise<HostRecord[]>;
export function DeleteHost(id: number): Promise<void>;
export function UpdateHost(id: number, host: HostConfig): Promise<void>;

export interface HostConfig {
    host: string;
    port: number;
    user: string;
    password: string;
}

export interface HostRecord {
    id: number;
    host: string;
    port: number;
    user: string;
    password: string;
}

export interface ExecutionTaskConfig {
    id: string;
    name: string;
    scripts: string[];
    hosts: HostConfig[];
    startedAt?: string;
    finishedAt?: string;
}

export interface CheckResult {
    host: string;
    running: boolean;
    residual: boolean;
    msg: string;
}

export interface ActionResult {
    host: string;
    error: string;
    msg: string;
    running: boolean;
}

export interface AnalysisSummary {
    id: string;
    name: string;
    scripts: string[];
    hasData: boolean;
    hasReport: boolean;
    logAvailable: boolean;
    dataDir: string;
    reportDir: string;
    reportHtmlUrl: string;
    downloadUrl: string;
    startedAt?: string;
    finishedAt?: string;
}

export interface OrchestrationConfig {
    sequence: string[];
    interval: number;
}

export interface AuditEntry {
    action: string;
    details: string;
    timestamp: string;
}

export interface OrchestrationProgress {
    taskId: string;
    taskName: string;
    step: string;
    status: string;
    error?: string;
    results?: ActionResult[];
    current: number;
    total: number;
}

// ========== iperf methods ==========

export function SaveIperfConfig(config: IperfConfig): Promise<void>;
export function GetIperfConfigs(): Promise<IperfConfig[]>;
export function GetIperfConfig(id: string): Promise<IperfConfig | null>;
export function DeleteIperfConfig(id: string): Promise<void>;
export function CreateIperfTask(task: IperfTask): Promise<void>;
export function GetIperfTasks(): Promise<IperfTask[]>;
export function DeleteIperfTask(id: string): Promise<void>;
export function StartIperfServer(host: HostConfig, port: number): Promise<ExecutionResult>;
export function StopIperfServer(host: HostConfig, port: number): Promise<ExecutionResult>;
export function CheckIperfServer(host: HostConfig, port: number): Promise<ExecutionResult>;
export function CheckIperfInstalled(hosts: HostConfig[]): Promise<ExecutionResult[]>;
export function RunIperfTest(taskID: string): Promise<void>;
export function StopIperfTest(taskID: string): Promise<void>;
export function CheckIperfTestStatus(taskID: string): Promise<string>;
export function IsIperfMonitorRunning(taskID: string): Promise<boolean>;
export function PullIperfData(taskID: string): Promise<void>;
export function GenerateIperfReport(taskID: string): Promise<void>;
export function GetIperfReportHTML(taskID: string): Promise<string>;
export function GetIperfAnalysisTasks(): Promise<IperfAnalysisSummary[]>;
export function CleanIperfLocal(taskID: string): Promise<void>;
export function CleanIperfRemote(taskID: string): Promise<void>;
export function GetIperfIntervals(taskID: string): Promise<IperfInterval[]>;

export interface IperfConfig {
    id: string;
    name: string;
    protocol: string;
    bandwidth: string;
    duration: number;
    parallel: number;
    blockSize: string;
    windowSize: string;
    reverse: boolean;
    bidir: boolean;
    extraFlags: string;
    serverTestIP: string;
    serverBindIP: string;
}

export interface IperfTask {
    id: string;
    name: string;
    config: IperfConfig;
    serverHost: HostConfig;
    clientHosts: HostConfig[];
    status: string;
    createdAt: string;
    startedAt?: string;
    finishedAt?: string;
}

export interface ExecutionResult {
    host: string;
    error: string;
    msg: string;
    running: boolean;
}

export interface IperfAnalysisSummary {
    taskId: string;
    taskName: string;
    serverHost: string;
    clientCount: number;
    status: string;
    hasData: boolean;
    hasReport: boolean;
    createdAt: string;
    avgBandwidth: number;
    maxBandwidth: number;
}

export interface IperfInterval {
    timestamp: number;
    streamID: number;
    duration: number;
    bytes: number;
    bitsPerSecond: number;
    jitterMs: number;
    lostPackets: number;
    totalPackets: number;
    retransmits: number;
    cpuUser: number;
    cpuSys: number;
}
